language: python

python:
  - 2.7
  - pypy

install:
  - pip install -r requirements.txt --use-mirrors
  - pip install .

# Run all the tests under /tests/
script:
  - nosetests tests/*
  - bin/whisper-create.py --help
  - bin/whisper-dump.py --help
  - bin/whisper-fetch.py --help
  - bin/whisper-info.py --help
  - bin/whisper-merge.py --help
  - bin/whisper-resize.py --help
  - bin/whisper-set-aggregation-method.py --help
  - bin/whisper-update.py --help
  - contrib/whisper-auto-update.py --help
  - contrib/whisper-auto-resize.py --help
